version: '2'
services:
    springangular-app:
        image: springangular
        environment:
            - _JAVA_OPTIONS=-Xmx512m -Xms256m
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:sqlserver://springangular-mssql:1433;database=SpringAngular
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    springangular-mssql:
        extends:
            file: mssql.yml
            service: springangular-mssql
